import assert from 'node:assert/strict';
import GLPK from 'glpk.js/node';
import {solveManualInputs,validateManualScenario} from '../src/manualOptimizer.ts';
const solver=await GLPK();
const geometry={type:'FeatureCollection',features:['g1','g2','n1','n2','z'].map(GRID_ID=>({type:'Feature',geometry:{type:'Point',coordinates:[0,0]},properties:{GRID_ID}}))};
const od=[['g1',[['1',1],['2',5]]],['g2',[['1',2],['2',4]]],['n1',[['1',1],['2',5]]],['n2',[['1',2],['2',4]]],['z',[['1',1],['2',2]]]];
const inputs={schemaVersion:2,mvcDemandStats:[['g1',1,10,10,1],['g2',1,10,10,5]],nonMvcDemandStats:[['n1',1,10,10,1],['n2',1,10,10,1]],mvcODByGrid:od,nonMvcODByGrid:od,mvcCapacity:[['1',10],['2',10]],nonMvcCapacity:[['1',10],['2',10]],mvcPaths250:[['1','g1',250],['2','g2',250]],mvcPaths500:[['2','g1',500],['1','g2',500]],zeroWorkloadSec:1};
const settings={mvcLower:0,mvcUpper:1.3,nonMvcLower:0,nonMvcUpper:1.3,maxPaths:250};
const weights={mvcTime:.8,mvcPaths:0,nonMvcTime:.2};
const stages=[];
const result=await solveManualInputs(inputs,geometry,weights,settings,solver,stage=>stages.push(stage));
assert.deepEqual(result.diagnostics.solver.candidateLimits,[16]);
assert.ok(stages.includes("Solving MVC allocation") && stages.includes("Solving Non-MVC allocation") && stages.includes("Allocating zero-incident grids"));
assert.equal(result.mvcGeojson.features.find(f=>f.properties.Grid_ID==='g1').properties.Allocated_Station,'2','Severity must change the count-only optimum');
assert.equal(result.travelTime[0].mvc,2.5,'Travel reporting must use severity weights');
assert.equal(result.assignedGrids,5);
assert.equal(result.nonMvcGeojson.features.filter(f=>f.properties.Demand_Type==='Zero-Incident Territory').length,1);
assert.ok(result.diagnostics.capacitySummary.every(r=>r.mvcWorkload>=0 && r.mvcWorkload<=13 && r.nonMvcHistoricalWorkload>=0 && r.nonMvcHistoricalWorkload<=13 && r.mvcWorkload+r.nonMvcHistoricalWorkload+r.zeroWorkload<=26));
const pathWeights={mvcTime:0,mvcPaths:.8,nonMvcTime:.2};
const paths250=await solveManualInputs(inputs,geometry,pathWeights,settings,solver);
const paths500=await solveManualInputs(inputs,geometry,pathWeights,{...settings,maxPaths:500},solver);
assert.equal(paths250.mvcGeojson.features.find(f=>f.properties.Grid_ID==='g1').properties.Allocated_Station,'1');
assert.equal(paths500.mvcGeojson.features.find(f=>f.properties.Grid_ID==='g1').properties.Allocated_Station,'2');
await assert.rejects(solveManualInputs({...inputs,zeroWorkloadSec:100},geometry,weights,settings,solver),/residual capacity/);
await assert.rejects(solveManualInputs({...inputs,mvcCapacity:[['1',1],['2',1]]},geometry,weights,settings,solver),/no eligible station/);
assert.throws(()=>validateManualScenario(weights,{...settings,mvcLower:1.1}),/no lower bound/);
assert.throws(()=>validateManualScenario({...weights,mvcTime:1},settings),/sum to/);
console.log('Passed: severity affects allocation; weighted reporting; upper-only capacity limits; 250/500 pool selection; residual zero capacity; infeasibility and input validation.');

const limited={...solver,solve:async(lp,options)=>lp.name.startsWith('Custom_') ? {result:{status:solver.GLP_UNDEF}} : solver.solve(lp,options)};
const fallback=await solveManualInputs(inputs,geometry,weights,settings,limited);
assert.equal(fallback.diagnostics.solver.heuristicFallback,true);
assert.equal(fallback.assignedGrids,5);
assert.ok(fallback.diagnostics.capacitySummary.every(r=>r.mvcWorkload<=r.mvcCapacity+0.01 && r.nonMvcHistoricalWorkload<=r.nonMvcCapacity+0.01));
console.log('Passed: capacity-checked fallback when solver returns no incumbent.');
